# Generated by Django 3.2.7 on 2021-11-10 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_auto_20211027_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakedgood',
            name='baked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bakedgood',
            name='good_type',
            field=models.CharField(choices=[('BG', 'Bagel'), ('BR', 'Bread'), ('CO', 'Cookie'), ('CA', 'Cake'), ('PR', 'Pretzel')], default='BG', max_length=2),
        ),
    ]
