# Generated by Django 3.2.7 on 2021-11-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_auto_20211110_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakedgood',
            name='baked_on',
        ),
    ]
