# Generated by Django 3.2.7 on 2021-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('example_app', '0005_bakedgood_baked_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('items', models.ManyToManyField(to='example_app.BakedGood')),
            ],
        ),
    ]
